# Generated by Django 2.2.4 on 2019-09-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='amount_available',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='У наявності'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
