# Generated by Django 2.2.4 on 2019-09-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190909_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='step1',
            field=models.FloatField(blank=True, null=True, verbose_name='Крок 1'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='step2',
            field=models.FloatField(blank=True, null=True, verbose_name='Крок 2'),
        ),
    ]
